### ISSUE TITLE
Possibiltiy of sharing inductive split data and negative samples for evaluation

### ISSUE THREAD

**Issue by jasperhyp** [kanz76/GMPNN-CS#2]
Hi!  Thanks for sharing your great work!  

Could you possibly share the inductive split dataset and also the negative samples used for evaluation?  I believe it's quite important for correctly benchmarking the model.  

I also noticed the fixed transductive split provided in SSI-DDI paper -- I would greatly appreciate it if the inductive split can be provided in that way too!

**Comment by kanz76** [comment]
Hi! Please refer to the file [data_preprocessing_cold_start.py](https://github.com/kanz76/GMPNN-CS/blob/master/data_preprocessing_cold_start.py) for the generation of the data.
